[workspace]
git_only = false
publish = true
release_always = false
semver_check = false
changelog_update = false
git_tag_enable = true
git_release_enable = false
pr_labels = ["release"]

[[package]]
name = "rune-server"
version_group = "alpha"
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = ["runectl", "rune-host-core", "rune-host-registry", "rune-host-runtime"]
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = true
git_release_name = "v{{ version }}"
git_release_type = "pre"
git_release_latest = false

[[package]]
name = "runectl"
version_group = "alpha"

