/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/src/**/*.rs", "./style/**/*.css"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low":          "#f1f3ff",
        "on-primary-fixed":               "#001947",
        "on-error-container":             "#93000a",
        "on-secondary-container":         "#57657a",
        "inverse-on-surface":             "#edf0ff",
        "tertiary-fixed-dim":             "#ffb59a",
        "on-secondary":                   "#ffffff",
        "on-primary-fixed-variant":       "#00419f",
        "secondary":                      "#515f74",
        "on-secondary-fixed":             "#0d1c2e",
        "surface-container":              "#e9edff",
        "primary-fixed-dim":              "#b1c5ff",
        "outline-variant":                "#c3c6d6",
        "surface-tint":                   "#1357c9",
        "tertiary":                       "#772600",
        "inverse-surface":                "#293040",
        "on-surface-variant":             "#434653",
        "outline":                        "#737785",
        "background":                     "#f9f9ff",
        "secondary-container":            "#d5e3fc",
        "tertiary-fixed":                 "#ffdbcf",
        "tertiary-container":             "#9e3500",
        "surface-variant":                "#dce2f7",
        "on-primary-container":           "#beceff",
        "surface-bright":                 "#f9f9ff",
        "on-surface":                     "#141b2b",
        "on-background":                  "#141b2b",
        "secondary-fixed":                "#d5e3fc",
        "on-primary":                     "#ffffff",
        "primary-fixed":                  "#dae2ff",
        "on-tertiary-fixed":              "#380d00",
        "inverse-primary":                "#b1c5ff",
        "surface-dim":                    "#d3daef",
        "on-error":                       "#ffffff",
        "primary":                        "#003b93",
        "error-container":                "#ffdad6",
        "on-tertiary-fixed-variant":      "#802a00",
        "primary-container":              "#0051c3",
        "surface-container-highest":      "#dce2f7",
        "surface-container-high":         "#e1e8fd",
        "error":                          "#ba1a1a",
        "surface":                        "#f9f9ff",
        "secondary-fixed-dim":            "#b9c7df",
        "on-tertiary":                    "#ffffff",
        "on-secondary-fixed-variant":     "#3a485b",
        "surface-container-lowest":       "#ffffff",
        "on-tertiary-container":          "#ffc1ab",
        "success":                        "#059669",
        "code-bg":                        "#111827",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      spacing: {
        "container-margin": "32px",
        "xl":     "32px",
        "sm":     "8px",
        "unit":   "4px",
        "lg":     "24px",
        "md":     "16px",
        "xs":     "4px",
        "gutter": "16px",
      },
      fontFamily: {
        sans:        ["Inter", "sans-serif"],
        mono:        ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter"],
        "body-sm":   ["Inter"],
        "body-md":   ["Inter"],
        "h1":        ["Inter"],
        "h2":        ["Inter"],
        "h3":        ["Inter"],
      },
      fontSize: {
        "mono":       ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm":    ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md":    ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "h3":         ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "h2":         ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1":         ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        "card": "0px 1px 3px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
